[theme]
# A dark, sophisticated color palette
primaryColor = "#2196f3"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1e1e1e"
textColor = "#ffffff"

[custom]
customCSS = """
/* Custom CSS goes here */
body {
    font-family: 'Roboto', sans-serif;
    background-color: #121212;
    color: #ffffff;
}

.stApp {
    background-color: #121212;
}

.stButton > button {
    background-color: #2196f3;
    color: #ffffff;
    border: none;
    border-radius: 4px;
    padding: 10px 20px;
    font-size: 16px;
    cursor: pointer;
}

.stButton > button:hover {
    background-color: #0d47a1;
}

.stTextInput > div > div > input {
    background-color: #1e1e1e;
    color: #ffffff;
    border: 1px solid #2196f3;
    border-radius: 4px;
    padding: 10px;
    font-size: 16px;
}

.stTextInput > div > div > input:focus {
    outline: none;
    border-color: #0d47a1;
}

/* Add more custom CSS for other components as needed */
"""
